name: Code style
on: [push, pull_request]
jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Check formatting
        uses: astral-sh/ruff-action@v3
        with:
          args: format --check --config .ruff.toml
      - name: Check coding style
        uses: astral-sh/ruff-action@v3
        with:
          args: check --output-format=github . --config .ruff.toml
